version: '3'
services:

  fpm:
    image: hudsonventura/phpondocker_with_pdo_oci
    build: PHPfpm
    volumes:
      - ./www:/var/www/html
      - ./configs:/usr/local/etc/php
    #environment:
    #  - ORACLE_HOME=/usr/local/instantclient


  nginx:
    build: Nginx
    volumes:
      - ./www:/var/www/html
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/app.vhost:/etc/nginx/conf.d/app.vhost
      - ./logs/Nginx:/var/log/nginx
      - ./configs/cert/:/etc/nginx/cert
    ports:
      - "80:80"
    #  - "443:443" -- to able the 443 and SSL, see README.md
