version: '3'
services:

  fpm:
    build: PHP7fpm
    volumes:
      - ./www:/var/www/html
      - ./server-configs:/usr/local/etc/php
    #environment:
    #  - ORACLE_HOME=/usr/local/instantclient


  nginx:
    build: Nginx
    volumes:
      - ./www:/var/www/html
      - ./server-configs/nginx.conf:/etc/nginx/nginx.conf
      - ./server-configs/app.vhost:/etc/nginx/conf.d/app.vhost
      - ./logs/Nginx:/var/log/nginx
      - ./server-configs/cert/:/etc/nginx/cert
    ports:
      - "80:80"
      - "443:443"
